# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'event_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_enter_event(object):
    def setupUi(self, enter_event):
        enter_event.setObjectName("enter_event")
        enter_event.resize(1502, 972)
        self.centralwidget = QtWidgets.QWidget(enter_event)
        self.centralwidget.setObjectName("centralwidget")
        self.new_event = QtWidgets.QPushButton(self.centralwidget)
        self.new_event.setGeometry(QtCore.QRect(70, 660, 381, 151))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.new_event.setFont(font)
        self.new_event.setObjectName("new_event")
        self.return_menu = QtWidgets.QPushButton(self.centralwidget)
        self.return_menu.setGeometry(QtCore.QRect(970, 660, 481, 151))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.return_menu.setFont(font)
        self.return_menu.setObjectName("return_menu")
        self.event_table = QtWidgets.QTableWidget(self.centralwidget)
        self.event_table.setGeometry(QtCore.QRect(320, 80, 581, 411))
        self.event_table.setObjectName("event_table")
        self.event_table.setColumnCount(3)
        self.event_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.event_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.event_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.event_table.setHorizontalHeaderItem(2, item)
        self.event_table.horizontalHeader().setDefaultSectionSize(190)
        self.edit_event = QtWidgets.QPushButton(self.centralwidget)
        self.edit_event.setGeometry(QtCore.QRect(480, 660, 451, 151))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.edit_event.setFont(font)
        self.edit_event.setObjectName("edit_event")
        enter_event.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(enter_event)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1502, 21))
        self.menubar.setObjectName("menubar")
        enter_event.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(enter_event)
        self.statusbar.setObjectName("statusbar")
        enter_event.setStatusBar(self.statusbar)

        self.retranslateUi(enter_event)
        QtCore.QMetaObject.connectSlotsByName(enter_event)

    def retranslateUi(self, enter_event):
        _translate = QtCore.QCoreApplication.translate
        enter_event.setWindowTitle(_translate("enter_event", "MainWindow"))
        self.new_event.setText(_translate("enter_event", "Create New Event"))
        self.return_menu.setText(_translate("enter_event", "Return to Main Menu"))
        item = self.event_table.horizontalHeaderItem(0)
        item.setText(_translate("enter_event", "Station"))
        item = self.event_table.horizontalHeaderItem(1)
        item.setText(_translate("enter_event", "Haul"))
        item = self.event_table.horizontalHeaderItem(2)
        item.setText(_translate("enter_event", "Haul_Date"))
        self.edit_event.setText(_translate("enter_event", "Edit Event"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    enter_event = QtWidgets.QMainWindow()
    ui = Ui_enter_event()
    ui.setupUi(enter_event)
    enter_event.show()
    sys.exit(app.exec_())
