# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 680)
        MainWindow.setStyleSheet("#MainWindow {\n"
"    background-image: url(:/bg_imgs/Images/LLsurvey2010_Leg3_otolith removal_DA (1).jpg);\n"
"    background-repeat: no-repeat; /* Prevents the image from tiling */\n"
"    background-position: center; /* Centers the image */\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.event_button = QtWidgets.QPushButton(self.centralwidget)
        self.event_button.setGeometry(QtCore.QRect(130, 500, 250, 110))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.event_button.setFont(font)
        self.event_button.setObjectName("event_button")
        self.enter_otolith = QtWidgets.QPushButton(self.centralwidget)
        self.enter_otolith.setGeometry(QtCore.QRect(400, 500, 250, 110))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.enter_otolith.setFont(font)
        self.enter_otolith.setObjectName("enter_otolith")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 30, 661, 171))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.enter_tag = QtWidgets.QPushButton(self.centralwidget)
        self.enter_tag.setGeometry(QtCore.QRect(670, 500, 250, 110))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.enter_tag.setFont(font)
        self.enter_tag.setObjectName("enter_tag")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.event_button.setText(_translate("MainWindow", "Enter Event"))
        self.enter_otolith.setText(_translate("MainWindow", "Enter Otolith"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">SableSpecimen</span></p></body></html>"))
        self.enter_tag.setText(_translate("MainWindow", "Enter Tag"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
from . import backgroundd_images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
