# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1102, 681)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.event_button = QtWidgets.QPushButton(self.centralwidget)
        self.event_button.setGeometry(QtCore.QRect(130, 500, 251, 111))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.event_button.setFont(font)
        self.event_button.setObjectName("event_button")
        self.enter_specimen = QtWidgets.QPushButton(self.centralwidget)
        self.enter_specimen.setGeometry(QtCore.QRect(680, 500, 231, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.enter_specimen.setFont(font)
        self.enter_specimen.setObjectName("enter_specimen")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -40, 1131, 721))
        self.label.setStyleSheet("background-image: url(Sablefish.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.event_button.raise_()
        self.enter_specimen.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.event_button.setText(_translate("MainWindow", "Enter Event"))
        self.enter_specimen.setText(_translate("MainWindow", "Enter Specimen"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))

