# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_event.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewEventWindow(object):
    def setupUi(self, NewEventWindow):
        NewEventWindow.setObjectName("NewEventWindow")
        NewEventWindow.resize(1431, 1002)
        self.centralwidget = QtWidgets.QWidget(NewEventWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.station = QtWidgets.QTextEdit(self.centralwidget)
        self.station.setGeometry(QtCore.QRect(140, 270, 271, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.station.setFont(font)
        self.station.setObjectName("station")
        self.haul = QtWidgets.QTextEdit(self.centralwidget)
        self.haul.setGeometry(QtCore.QRect(470, 270, 291, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.haul.setFont(font)
        self.haul.setObjectName("haul")
        self.date = QtWidgets.QTextEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(850, 270, 431, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.date.setFont(font)
        self.date.setObjectName("date")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 200, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 190, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(920, 190, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.add_event = QtWidgets.QPushButton(self.centralwidget)
        self.add_event.setGeometry(QtCore.QRect(260, 680, 251, 141))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.add_event.setFont(font)
        self.add_event.setObjectName("add_event")
        self.return_to_event_select = QtWidgets.QPushButton(self.centralwidget)
        self.return_to_event_select.setGeometry(QtCore.QRect(840, 680, 331, 141))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.return_to_event_select.setFont(font)
        self.return_to_event_select.setObjectName("return_to_event_select")
        NewEventWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NewEventWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1431, 21))
        self.menubar.setObjectName("menubar")
        NewEventWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NewEventWindow)
        self.statusbar.setObjectName("statusbar")
        NewEventWindow.setStatusBar(self.statusbar)

        self.retranslateUi(NewEventWindow)
        QtCore.QMetaObject.connectSlotsByName(NewEventWindow)

    def retranslateUi(self, NewEventWindow):
        _translate = QtCore.QCoreApplication.translate
        NewEventWindow.setWindowTitle(_translate("NewEventWindow", "MainWindow"))
        self.label.setText(_translate("NewEventWindow", "Station Number"))
        self.label_2.setText(_translate("NewEventWindow", "Haul Number"))
        self.label_3.setText(_translate("NewEventWindow", "Haul Date"))
        self.add_event.setText(_translate("NewEventWindow", "Add Event"))
        self.return_to_event_select.setText(_translate("NewEventWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewEventWindow = QtWidgets.QMainWindow()
    ui = Ui_NewEventWindow()
    ui.setupUi(NewEventWindow)
    NewEventWindow.show()
    sys.exit(app.exec_())
