# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oto_event_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Select_Event(object):
    def setupUi(self, Select_Event):
        Select_Event.setObjectName("Select_Event")
        Select_Event.resize(824, 470)
        self.event_table = QtWidgets.QTableWidget(Select_Event)
        self.event_table.setGeometry(QtCore.QRect(200, 0, 371, 311))
        self.event_table.setObjectName("event_table")
        self.event_table.setColumnCount(3)
        self.event_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.event_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.event_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.event_table.setHorizontalHeaderItem(2, item)
        self.event_table.horizontalHeader().setDefaultSectionSize(120)
        self.select_button = QtWidgets.QPushButton(Select_Event)
        self.select_button.setGeometry(QtCore.QRect(110, 340, 211, 91))
        self.select_button.setObjectName("select_button")
        self.cancel_button = QtWidgets.QPushButton(Select_Event)
        self.cancel_button.setGeometry(QtCore.QRect(440, 340, 211, 91))
        self.cancel_button.setObjectName("cancel_button")

        self.retranslateUi(Select_Event)
        QtCore.QMetaObject.connectSlotsByName(Select_Event)

    def retranslateUi(self, Select_Event):
        _translate = QtCore.QCoreApplication.translate
        Select_Event.setWindowTitle(_translate("Select_Event", "Dialog"))
        item = self.event_table.horizontalHeaderItem(0)
        item.setText(_translate("Select_Event", "Station Number"))
        item = self.event_table.horizontalHeaderItem(1)
        item.setText(_translate("Select_Event", "Haul Number"))
        item = self.event_table.horizontalHeaderItem(2)
        item.setText(_translate("Select_Event", "Haul Date"))
        self.select_button.setText(_translate("Select_Event", "Select"))
        self.cancel_button.setText(_translate("Select_Event", "Cancel"))
