# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sample_collection.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sample_collections(object):
    def setupUi(self, sample_collections):
        sample_collections.setObjectName("sample_collections")
        sample_collections.resize(672, 452)
        self.pushButton = QtWidgets.QPushButton(sample_collections)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(sample_collections)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 20, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(sample_collections)
        self.pushButton_3.setGeometry(QtCore.QRect(440, 20, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(sample_collections)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 130, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(sample_collections)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 130, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(sample_collections)
        self.pushButton_6.setGeometry(QtCore.QRect(440, 130, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(sample_collections)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 240, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(sample_collections)
        self.pushButton_8.setGeometry(QtCore.QRect(230, 240, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(sample_collections)
        self.pushButton_9.setGeometry(QtCore.QRect(440, 240, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(sample_collections)
        self.pushButton_10.setGeometry(QtCore.QRect(470, 360, 151, 71))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(sample_collections)
        self.pushButton_11.setGeometry(QtCore.QRect(30, 360, 151, 71))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(sample_collections)
        self.pushButton_12.setGeometry(QtCore.QRect(310, 360, 151, 71))
        self.pushButton_12.setObjectName("pushButton_12")

        self.retranslateUi(sample_collections)
        QtCore.QMetaObject.connectSlotsByName(sample_collections)

    def retranslateUi(self, sample_collections):
        _translate = QtCore.QCoreApplication.translate
        sample_collections.setWindowTitle(_translate("sample_collections", "Dialog"))
        self.pushButton_10.setText(_translate("sample_collections", "Confirm"))
        self.pushButton_11.setText(_translate("sample_collections", "Clear"))
        self.pushButton_12.setText(_translate("sample_collections", "Cancel"))
